# Generated by Django 4.2.7 on 2025-05-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='firm',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='license',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='specialization',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
