# Generated by Django 4.2.7 on 2025-05-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_lawyerprofile_firm_alter_lawyerprofile_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='per_case_charge',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
    ]
