# Generated by Django 4.2.7 on 2025-05-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='participants',
        ),
        migrations.AddField(
            model_name='thread',
            name='participant',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
