# Generated by Django 4.2.7 on 2025-05-18 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_remove_message_thread_remove_thread_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='participant',
        ),
        migrations.AddField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
