# Generated by Django 4.2.7 on 2025-05-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_message_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='case',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
            preserve_default=False,
        ),
    ]
