# Generated by Django 4.2.7 on 2025-05-20 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_remove_thread_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='case',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
            preserve_default=False,
        ),
    ]
