# Generated by Django 4.2.7 on 2025-05-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_thread_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='case',
        ),
    ]
