# Generated by Django 4.2.7 on 2025-05-20 16:36

import apps.cases.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0009_thread_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_by',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='case',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_shared',
        ),
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to=apps.cases.models.upload_to),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.folder'),
        ),
    ]
