# Generated by Django 4.2.7 on 2025-05-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_caserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserequest',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case'),
        ),
    ]
