# Generated by Django 4.2.7 on 2025-05-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('appointment', 'Appointment'), ('document', 'Document'), ('case', 'Case'), ('invoice', 'Invoice'), ('request', 'Request')], max_length=20),
        ),
    ]
